server:
  port: 7000
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/demo
logging:
  level:
    root: info
    sun:
      rmi: info
      net:
        www:
          protocol:
            http: debug
    nl:
      edsn:
        prototype:
          devnationclient: debug
    org:
      springframework:
        web:
          client: debug
      apache:
        http: debug
